name: Pytest for TSUMUGI

on:
    push:

jobs:
    unit_tests:
        name: Unit tests for TSUMUGI
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 2
            matrix:
                os: [ubuntu-latest, macos-latest]
                python-version: ["3.12"]

        defaults:
            run:
                shell: bash -l {0}

        steps:
            - uses: actions/checkout@v4

            - name: Set up Miniconda
              uses: conda-incubator/setup-miniconda@v3
              with:
                  python-version: ${{ matrix.python-version }}
                  miniconda-version: "latest"
                  activate-environment: env-tsumugi
                  channels: conda-forge, bioconda, defaults

            - name: Create and activate conda environment
              run: |
                  conda install -y python=${{ matrix.python-version }} pip pytest
                  python -V

            - name: Install TSUMUGI and dependencies
              run: |
                  pip install -e .

            - name: Execute specific test case
              env:
                  PYTHONPATH: src
              run: |
                  pytest tests/ -p no:warnings -vv
